### ISSUE TITLE
SPF fail when sending to a SimpleLogin hosted address

### ISSUE THREAD

**Issue by pH142857** [simple-login/app#1556]
## Prerequisites
- [X] I have searched open and closed issues to make sure that the bug has not yet been reported.

## Bug report
When sending an email from a specific address hosted by gandi.net, to objections_strc@aleeas.com hosted by simplelogin.io, sender receives a Mail Delivery Report and mail doesn't reach destination. The mail delivery report states:
```
<objections_strc@aleeas.com>: host mx1.simplelogin.co[176.119.200.132] said:
550 5.7.23 <objections_strc@aleeas.com>: Recipient address rejected:
Message rejected due to: SPF fail - not authorized. Please see
http://www.openspf.net/Why?s=mfrom;id=[REDACTED];ip=217.70.183.193;r=<UNKNOWN>
(in reply to RCPT TO command)
```
(`[REDACTED]` by me)

**Expected behavior**
Mail being received by objections_strc@aleeas.com.

**Additional context**
It doesn't happen for other mails sent and received by objections_strc@aleeas.com.
I contacted gandi.net support and they found [these errors](https://mxtoolbox.com/SuperTool.aspx?action=dkim%3aaleeas.com%3agm1&run=toolpage) and told me to contact simplelogin.

**Comment by jeifour** [comment]
The [purported issues](https://mxtoolbox.com/SuperTool.aspx?action=dkim%3aaleeas.com%3agm1&run=toolpage) seem unrelated. First, as you have described, from SimpleLogin's point of view this would be an issue with receiving mail, but this tool checks for a DKIM entry of SimpleLogin's domain, which only concerns outgoing mail. Second, this is not actually an issue, as DKIM "gm1" is not used by aleeas.com, only "[dkim](https://mxtoolbox.com/SuperTool.aspx?action=dkim%3aaleeas.com%3adkim&run=toolpage)".

What would be important to debug this issue is the SPF entry on your domain, which you didn't publish here. Please check if the IP 217.70.183.193 is allowed to send emails for your domain with a tool like https://vamsoft.com/support/tools/spf-policy-tester.

**Comment by pH142857** [comment]
Thanks for your answer.

The DNS SPF & DMARC entries on my domain are as such:

```
@ 10800 IN TXT "v=spf1 mx -all"
_dmarc 10800 IN TXT "v=DMARC1; p=reject; rua=mailto:dmarc.[REDACTED]@le-pic.org; ruf=mailto:postmaster@le-pic.org"
_dmarc.listes 10800 IN TXT "v=DMARC1; p=reject; rua=mailto:dmarc.listes.[REDACTED]@le-pic.org; ruf=mailto:postmaster@le-pic.org"
```

The [SPF tool](https://vamsoft.com/support/tools/spf-policy-tester) for IP 217.70.183.193 and my inbox contact@[REDACTED].fr says `SPF fail`. The full trace is available [here](https://secrets.le-pic.org/?5561cbb6a2202e19#7qAL7EyH9WBc7CygS5Ws12Xd1zNfPhoicEi3RRJxQTx2) for a week.

NB : `[REDACTED]` is hiding my domain; `le-pic.org` is my hoster (Gandi is just the registrar here).

I'm not sure what this means. Is the problem on the hoster's side?

**Comment by pH142857** [comment]
Thanks a lot, it's now solved!
