### ISSUE TITLE
Recovery code security

### ISSUE THREAD

**Issue by developStorm** [simple-login/app#198]
https://medium.com/@harwoeck/password-and-credential-management-in-2018-56f43669d588#39ab

#195

**Comment by nguyenkims** [comment]
@developStorm I also asked myself whether we should encrypt the recovery code and after consulting implementations of different websites (yubico, google, slack, etc), it seems that they all store the recovery code in clear text. That probably makes sense given the TOTP secret code is also stored as cleartext (as otherwise we cannot generate the token). 

Another reason is as the password is stored with a salt and hash, in the worst case a bad guy has access to the database dump, he will be stopped at the first login step anyway.
