### ISSUE TITLE
MX server cipher suite support.

### ISSUE THREAD

**Issue by FozzieHi** [simple-login/app#245]
I recently ran a scan `on mx1.simplelogin.co` and found a number of unusual ciphers in use.

Firstly we have TLS 1.1 enabled with the following ciphers:
```
TLS_DHE_RSA_WITH_AES_128_CBC_SHA
TLS_DHE_RSA_WITH_AES_256_CBC_SHA
TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA
TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA
```
TLS 1.1 should be disabled completely and is deprecated in a number of applications.

We then have TLS 1.2 enabled with the following ciphers:
```
TLS_DHE_RSA_WITH_AES_128_CBC_SHA
TLS_DHE_RSA_WITH_AES_128_CBC_SHA256
TLS_DHE_RSA_WITH_AES_128_CCM
TLS_DHE_RSA_WITH_AES_128_CCM_8
TLS_DHE_RSA_WITH_AES_128_GCM_SHA256
TLS_DHE_RSA_WITH_AES_256_CBC_SHA
TLS_DHE_RSA_WITH_AES_256_CBC_SHA256
TLS_DHE_RSA_WITH_AES_256_CCM
TLS_DHE_RSA_WITH_AES_256_CCM_8
TLS_DHE_RSA_WITH_AES_256_GCM_SHA384
TLS_DHE_RSA_WITH_ARIA_128_GCM_SHA256
TLS_DHE_RSA_WITH_ARIA_256_GCM_SHA384
TLS_DHE_RSA_WITH_CHACHA20_POLY1305_SHA256
TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA
TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256
TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA
TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384
TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
TLS_ECDHE_RSA_WITH_ARIA_128_GCM_SHA256
TLS_ECDHE_RSA_WITH_ARIA_256_GCM_SHA384
TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256
```
Many of these ciphers are weak and deprecated, the issue here is that we're not enforcing the cipher suite order on the server side so older clients which support more secure ciphers may end up using weaker ones as they are higher in the preference list. We should either remove the weak ciphers or make the list server prefered with the ciphers in the order of strength.

TLS 1.3 support is fine as all of the ciphers are considered secure.

I propose implementing the following ciphers for TLS 1.2 as a client preferred list:
```
TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256
```
All of these ciphers are currently considered secure and we shouldn't run into any compatibility issues as Google's MX's cipher list is simply `TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256` for TLS 1.2.

**Comment by nguyenkims** [comment]
@FozzieHi thanks for the suggestion! Currently we are using hardenize as the referent to assert the security level of SimpleLogin MX servers. For example this is a report on SimpleLogin https://www.hardenize.com/report/simplelogin.io/1595745293

As soon as TLSv1.1 is deprecated on hardenize, we'll remove TLSv1.1 support. We track these security updates in this ticket on SimpleLogin roadmap https://trello.com/c/9i4pXyuH/79-enforce-mail-server. I added a link to this Github issue so we can  use your recommended list when updating the cipher suites :).

Since email softwares can be outdated (usually happen with small MX servers), we choose the approach "weak encryption is better than no encryption" to make sure SimpleLogin is compatible with most of email servers out there. 

I'll close this issue for now but it'll be take into account by the time we work on https://trello.com/c/9i4pXyuH/79-enforce-mail-server.
