### ISSUE TITLE
Massive email delays

### ISSUE THREAD

**Issue by FozzieHi** [simple-login/app#258]
Getting delays of upwards of 4 hours, is this fixed now and is there just a backlog of emails waiting to be sent?

**Comment by nguyenkims** [comment]
@FozzieHi yes due to an issue yesterday, a lot of emails are having important delays. The server is still processing the non-sending emails, we have btw increased the server capacity 4x to speed this up. I think all emails should be finished processing in about 30 minutes, after that email delivery speed should be normal again.

If you have a domain, you can change the MX priority to put mx2.simplelogin.co in front of mx1.simplelogin.co instead as this one isn't affected by the bug yesterday.

**Comment by LagSeeN** [comment]
same mail delay  3 hours

**Comment by nguyenkims** [comment]
@FozzieHi  @LagSeeN the delay should be resolved now.

**Comment by LagSeeN** [comment]
@nguyenkims Thank you
