### ISSUE TITLE
Password reset doesn't arrive

### ISSUE THREAD

**Issue by asmagen** [simple-login/app#262]
I'm requesting password reset email and I don't receive any -- how can I reset my password ASAP?

**Comment by nguyenkims** [comment]
@asmagen sorry for the late response! Sometimes emails can have delays, mostly due to the "greylisting" https://en.wikipedia.org/wiki/Greylisting_(email)#:~:text=Greylisting%20is%20a%20method%20of,sender%20it%20does%20not%20recognize. used by email services.

Can you retry and let me know if the problem still persists?

**Comment by pojhm91c7iwk** [comment]
So even the new email account verification doesn't arrive (I will still wait as per @nguyenkims's recommendation). However, can we manually approve account/reset passwords by updating the db?

**Comment by nguyenkims** [comment]
@pojhm91c7iwk currently there's no convenient way to reset a password directly in the database: we explicitly made that choice to protect users :). Can you send me your account's email that you want to reset the password for? You can reach me at hi [at] simplelogin.io

**Comment by pojhm91c7iwk** [comment]
> @pojhm91c7iwk currently there's no convenient way to reset a password directly in the database: we explicitly made that choice to protect users :). Can you send me your account's email that you want to reset the password for? You can reach me at hi [at] simplelogin.io

So this is for self-hosted instance, after going through all the steps, I sign-up for a new account in my self-hosted instance. It says it sent a verification email but I have still not received it. I tried with multiple address and no verification email arrived. Because I have access to my db, I was wondering if I can skip pass the "verification email" process (just like changin the lifetime value in db to True from False.

**Comment by pojhm91c7iwk** [comment]
I was able to bypass the verification email by changing the value in the db.
