### ISSUE TITLE
UI Issues on the Firefox Extension

### ISSUE THREAD

**Issue by axian32** [simple-login/app#268]
Hello! I've been loving this service so far!
One problem I've had though is that the UI on the Firefox extension cuts off a chunk of the right side, blocking most of the "Dashboard" button and the endings of the longer alias emails. This can be inconvenient at times.

**Comment by ngxson** [comment]
@axian32 Hi, thanks for reporting to us. This problem comes when we place SimpleLogin's extension inside "Overflow Menu". I'm still looking for solution.

In fact, Firefox designed this menu very poorly so not just us, but many other extensions face the same issue
![image](https://user-images.githubusercontent.com/7702203/91037397-3bc3c000-e609-11ea-90d8-578e0ef2cb47.png)

**Comment by ngxson** [comment]
fixed on https://github.com/simple-login/browser-extension/pull/52

**Comment by nguyenkims** [comment]
@axian32 we have released a new version v2.2.0 that has fixed this layout issue :)
