### ISSUE TITLE
Migration error on SQLite

### ISSUE THREAD

**Issue by doanguyen** [simple-login/app#4]
SQLite supports a limited subset of `ALTER TABLE` which does not include the `ALTER COLUMN` feature, this migration (and many others) will fail under SQLite engine:

https://github.com/simple-login/app/blob/774b5b721223eef590cc5733d4c47a8be57e1440/migrations/versions/213fcca48483_.py#L20

I found no easy solution yet, except to manually write the migrations (yet it is a lot of work). For me, the best way is providing a SQL schema so people using SQLite can import directly into their database without using the migration from alembic, others may use the migration normally.

**Comment by nguyenkims** [comment]
Ah actually the database creation in Sqlite doesn't use migration, it uses directly `db.create_all()` (cf `fake_data()` method). This is because Sqlite doesn't handle well the migration. As `sqlite` is only used during development, the database is deleted and re-populated at each run.

The column rename is not handled well by migration as it's not intelligent enough to know that 1. first it needs to create a new column 2. copy the current column data over to the new one 3. drop the current column.

**Comment by doanguyen** [comment]
Oh, I see the `fake_data` method now. It would be great if this get mentioned somewhere in the docs?

**Comment by nguyenkims** [comment]
I just updated the README to add a small section about local environment. I'll close this issue then.
