### ISSUE TITLE
Any tips for blacklist/timeouts?

### ISSUE THREAD

**Issue by havedill** [simple-login/app#49]
Any tips if my AWS IP appears on spamhaus blacklist?

Also, occasionally after a few emails forward, i start getting timeouts to googles smtp servers. Is there a fix for this?

```
.google.com[172.217.197.26]:25: Connection timed out
Jan 24 10:44:55 ip-172-31-59-45 postfix/smtp[19445]: connect to alt1.gmail-smtp-in.l.google.com[64.233.186.27]:25: Connection timed out
Jan 24 10:45:25 ip-172-31-59-45 postfix/smtp[19445]: connect to alt2.gmail-smtp-in.l.google.com[209.85.202.27]:25: Connection timed out
Jan 24 10:45:55 ip-172-31-59-45 postfix/smtp[19445]: connect to alt3.gmail-smtp-in.l.google.com[66.102.1.27]:25: Connection timed out
Jan 24 10:46:25 ip-172-31-59-45 postfix/smtp[19445]: connect to alt4.gmail-smtp-in.l.google.com[172.217.218.27]:25: Connection timed out

```

**Comment by havedill** [comment]
Alright so i already had an SES account from a while back.

I followed this guide:
https://docs.aws.amazon.com/ses/latest/DeveloperGuide/postfix.html

but in my /etc/postfix/main.cf, i had to change this value to "may" from encrypt. Looks like im whitelisted now

`smtp_tls_security_level = may`

**Comment by nguyenkims** [comment]
@havedill Currently you can set the `POSTFIX_SERVER` in the config file to choose another outgoing SMTP server: https://github.com/simple-login/app/blob/master/example.env#L41

I never used SES before, if you happen to know it well, I would really appreciate if you could create a PR to add the support for SES! Otherwise we can add it to our roadmap and look at it later. 

> Any tips if my AWS IP appears on spamhaus blacklist?

I guess the only solution is to whitelist the IP yourself on the corresponding blacklist. We have actually quit AWS to move to another cloud provider (UpCloud) as their IPs are quite "dirty" for sending emails and we were tired of going whitelisting these IPs.
