### ISSUE TITLE
[Request] Bulk move alias's to a different mail box

### ISSUE THREAD

**Issue by browntownington** [simple-login/app#627]
Presently I can see a way to move alias's in a bulk or batch way - though maybe I am looking in the wrong place?
I have over 200+ alias, but in another year I could have 1000+
Manually moving an alias to a different mailbox is extremely tedious. 

On a side note:
duckduckgo has released duck.com a service which removes trackers from emails. This is the premise which I wish to migrate to a new mailbox. However if a user wishes to move to a different mailbox they would have the same issue.

**Comment by nguyenkims** [comment]
@browntownington bulk editing is indeed one of the most requested feature that you can track on https://github.com/simple-login/app/discussions/407 

To move aliases to a different mailbox, I'd recommend changing an existing mailbox address instead of creating a new mailbox. This way all existing aliases will be moved to the new mailbox.

**Comment by browntownington** [comment]
Thanks @nguyenkims that is a hot tip! And a very reasonable work around! Thank you!
