### ISSUE TITLE
SPF/DMARC rules are too strict

### ISSUE THREAD

**Issue by dannytech** [simple-login/app#642]
## Prerequisites
- [x] I have searched open and closed issues to make sure that the bug has not yet been reported.

## Bug report

**Describe the bug**
Hi, I noticed that the SPF and DMARC validation steps (the others do this too, but I think it's less of an issue there) require an exact string match to what's expected, which might not always be the case. As an example, I use [DNSControl](https://stackexchange.github.io/dnscontrol/) to manage my DNS, which uses a DMARC builder (near the end of [this page](https://stackexchange.github.io/dnscontrol/js)) to generate a DMARC record. The record it builds differs slightly from the SimpleLogin one, in that it excludes `pct=100`. The default value for `pct` is 100, so DNSControl simply drops it from being explicitly defined, meaning that even though these differ in syntax, they are functionally identical.

```
Mine: v=DMARC1; p=quarantine; adkim=s; aspf=s
SL: v=DMARC1; p=quarantine; pct=100; adkim=s; aspf=s
```

There is also likely a similar issue with SPF, in that as far as I'm aware an SPF record can contain multiple `include`s for different senders, so that would mean that if someone wants to add another email server which can send from their custom domain, adding an additional `include`, this would make SimpleLogin consider it incorrect.

**Expected behavior**
Ideally, SimpleLogin should parse the DNS records to make sure that even if the syntax does not match exactly, the policy itself is compliant. This is more of a nitpick than anything, it's still possible to use a custom domain even when SimpleLogin considers it incorrect.

**Screenshots**
![image](https://user-images.githubusercontent.com/20747523/136633792-01fc692a-3a77-4fc0-b777-7f2af394d6c0.png)

**Comment by WhamboMPS** [comment]
I am very familiar with the various email authentication technologies including those mentioned by @dannytech in this post (though, as a non-engineer, I am not conversant in the technical details which he has so clearly laid out). My compliments go to him for so clearly detailing the issue.

In general I am highly complimentary of SL including authentication technologies in its system and definitely would like to see them retained. Conversely, while I do not share Mr. Helstern's technical chops, everything he is documenting appears accurate to me. My key request would be that the imperfect exact match system currently in use not be deprecated simply because the unquestionably better parsing system has not been built.

When considering this bug/feature enhancement I would suggest that it be remembered that email authentication technologies like SPF and DMARC are used for _outbound_ email, not inbound, and, of course, SL is primarily designed to solve for the inbound email use case. Therefore, while Mr. Helstern's comments appear valid, they might also be considered a bit of a corner case. As a non-programmer my presumption is that enhancing the authentication technologies to solve for this issue in the manner which he described wouldn't be an enormous technical lift, but neither would it be a "trivial" exercise. While enhancing the authentication system to support inexact matches _would_ make SL a better system, I certainly would not prioritize it as highly as some of the other enhancements that have been posted in this forum.

@dannytech recommends parsing the DNS so that non-exact matches for DMARC and SPF can be passed as long as they meet the minimum requirements. Perhaps someone can share parsing logic (or code) that already achieves this goal. Or, for the many amongst you who can rightfully mock the lack of programming skills that characterize us marketers (hey - I resemble that remark!), perhaps you may want to take a crack at writing some snippets of code that can be included in SL's product. Just a thought...

**Comment by JGKle** [comment]
Just wondering why this was marked as "completed"? I'm a new user, running into the same issue with SPF in 2025 - namely I have a few includes in my SPF, which SimpleLogin marks as incorrect. Can this be reopened until completed? 🤔
